services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xrkr80hd-suite-app
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    volumes:
      - uploads_data:/var/www/html/public/uploads
      - sqlite_data:/var/www/html/database
    restart: unless-stopped

volumes:
  uploads_data:
  sqlite_data:
